### ISSUE TITLE
Nowa diagnoza społeczna

### ISSUE THREAD

**Issue by BERENZ** [pbiecek/Diagnoza#2]
Pojawiła się Diagnoza Społeczna 2015. Postaram się uaktualnić pakiet o nowe zbiory (dziś wieczorem lub jutro w ciągu dnia).

Pozdr,
MB

**Comment by pbiecek** [comment]
Super

W dniu 24 listopada 2015 17:51 użytkownik Maciej Beręsewicz <
notifications@github.com> napisał:

> Pojawiła się Diagnoza Społeczna 2015. Postaram się uaktualnić pakiet o
> nowe zbiory (dziś wieczorem lub jutro w ciągu dnia).
>
> Pozdr,
> MB
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pbiecek/Diagnoza/issues/2>.
>



-- 
pozdrawiam serdecznie,
Przemysław Biecek

**Comment by BERENZ** [comment]
Czy dane mogą być

**Comment by pbiecek** [comment]
tbl_df jest ok, ale chyba trzeba dodać wtedy dplyr w zależnościach.
Zmień też wersję pakietu a na GitHub można zrobić nowy release

**Comment by pbiecek** [comment]
Ok, widzę, że już zmieniłeś. Świetnie
