### ISSUE TITLE
long vectors przy instalacji

### ISSUE THREAD

**Issue by blakocha** [pbiecek/Diagnoza#7]
Panowie, czy można prosić o podpowiedź dotyczącą poniższego błędu przy instalacji Diagnoza. Długie wektory nie są wspierane. Więc co robić?

* installing *source* package 'Diagnoza' ...
** data
*** moving datasets to lazyload DB
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  : 
  długie wektory nie są jeszcze wspierane: connections.c:5671
ERROR: lazydata failed for package 'Diagnoza'
* removing 'C:/Users/blaze/OneDrive/Dokumenty/R/win-library/3.4/Diagnoza'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by pbiecek** [comment]
Proszę wkleić poniżej wynik funkcji sessionInfo()

**Comment by blakocha** [comment]
> install_github("pbiecek/Diagnoza")
Downloading GitHub repo pbiecek/Diagnoza@master
from URL https://api.github.com/repos/pbiecek/Diagnoza/zipball/master
Installing Diagnoza
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/blaze/AppData/Local/Temp/RtmpcBWVUQ/devtools3bb4304b4f51/pbiecek-Diagnoza-415fddd"  \
  --library="C:/Users/blaze/OneDrive/Dokumenty/R/win-library/3.4" --install-tests 

* installing *source* package 'Diagnoza' ...
** data
*** moving datasets to lazyload DB
Error in lazyLoadDBinsertVariable(vars[i], from, datafile, ascii, compress,  : 
  długie wektory nie są jeszcze wspierane: connections.c:5671
ERROR: lazydata failed for package 'Diagnoza'
* removing 'C:/Users/blaze/OneDrive/Dokumenty/R/win-library/3.4/Diagnoza'
In R CMD INSTALL
Installation failed: Command failed (1)
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250   
[3] LC_MONETARY=Polish_Poland.1250 LC_NUMERIC=C                  
[5] LC_TIME=Polish_Poland.1250    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.4

loaded via a namespace (and not attached):
 [1] httr_1.3.1     compiler_3.4.3 R6_2.2.2       tools_3.4.3    withr_2.1.1    rstudioapi_0.7
 [7] curl_3.1       memoise_1.1.0  git2r_0.21.0   digest_0.6.13

**Comment by blakocha** [comment]
Panowie, jakiekolwiek podpowiedzi mile widziane :-). Czy też powinienem porzucić wszelką nadzieję?

**Comment by pbiecek** [comment]
Spróbuj teraz, wyłączyłem lazy load
```
install_github("pbiecek/Diagnoza")
```
po zainstalowaniu i załadowaniu pakietu, trzeba dołączyć zbiory danych jawnie, poleceniami
```
library("Diagnoza")
data("osoby")
data("osobyDict")
data("gospodarstwa")
data("gospodarstwaDict")
```

**Comment by blakocha** [comment]
Działa! Dzięki!
